// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grasp_event.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_grasp_5fevent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_grasp_5fevent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_grasp_5fevent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_grasp_5fevent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_grasp_5fevent_2eproto;
namespace gazebo {
namespace msgs {
class GraspEvent;
class GraspEventDefaultTypeInternal;
extern GraspEventDefaultTypeInternal _GraspEvent_default_instance_;
}  // namespace msgs
}  // namespace gazebo
PROTOBUF_NAMESPACE_OPEN
template<> ::gazebo::msgs::GraspEvent* Arena::CreateMaybeMessage<::gazebo::msgs::GraspEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gazebo {
namespace msgs {

// ===================================================================

class GraspEvent PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gazebo.msgs.GraspEvent) */ {
 public:
  inline GraspEvent() : GraspEvent(nullptr) {};
  virtual ~GraspEvent();

  GraspEvent(const GraspEvent& from);
  GraspEvent(GraspEvent&& from) noexcept
    : GraspEvent() {
    *this = ::std::move(from);
  }

  inline GraspEvent& operator=(const GraspEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraspEvent& operator=(GraspEvent&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GraspEvent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraspEvent* internal_default_instance() {
    return reinterpret_cast<const GraspEvent*>(
               &_GraspEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GraspEvent& a, GraspEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(GraspEvent* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraspEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraspEvent* New() const final {
    return CreateMaybeMessage<GraspEvent>(nullptr);
  }

  GraspEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraspEvent>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GraspEvent& from);
  void MergeFrom(const GraspEvent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraspEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gazebo.msgs.GraspEvent";
  }
  protected:
  explicit GraspEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_grasp_5fevent_2eproto);
    return ::descriptor_table_grasp_5fevent_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArmFieldNumber = 1,
    kObjectFieldNumber = 2,
    kAttachedFieldNumber = 3,
  };
  // required string arm = 1;
  bool has_arm() const;
  private:
  bool _internal_has_arm() const;
  public:
  void clear_arm();
  const std::string& arm() const;
  void set_arm(const std::string& value);
  void set_arm(std::string&& value);
  void set_arm(const char* value);
  void set_arm(const char* value, size_t size);
  std::string* mutable_arm();
  std::string* release_arm();
  void set_allocated_arm(std::string* arm);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_arm();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_arm(
      std::string* arm);
  private:
  const std::string& _internal_arm() const;
  void _internal_set_arm(const std::string& value);
  std::string* _internal_mutable_arm();
  public:

  // required string object = 2;
  bool has_object() const;
  private:
  bool _internal_has_object() const;
  public:
  void clear_object();
  const std::string& object() const;
  void set_object(const std::string& value);
  void set_object(std::string&& value);
  void set_object(const char* value);
  void set_object(const char* value, size_t size);
  std::string* mutable_object();
  std::string* release_object();
  void set_allocated_object(std::string* object);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_object();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_object(
      std::string* object);
  private:
  const std::string& _internal_object() const;
  void _internal_set_object(const std::string& value);
  std::string* _internal_mutable_object();
  public:

  // required bool attached = 3;
  bool has_attached() const;
  private:
  bool _internal_has_attached() const;
  public:
  void clear_attached();
  bool attached() const;
  void set_attached(bool value);
  private:
  bool _internal_attached() const;
  void _internal_set_attached(bool value);
  public:

  // @@protoc_insertion_point(class_scope:gazebo.msgs.GraspEvent)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr arm_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr object_;
  bool attached_;
  friend struct ::TableStruct_grasp_5fevent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GraspEvent

// required string arm = 1;
inline bool GraspEvent::_internal_has_arm() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GraspEvent::has_arm() const {
  return _internal_has_arm();
}
inline void GraspEvent::clear_arm() {
  arm_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& GraspEvent::arm() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.GraspEvent.arm)
  return _internal_arm();
}
inline void GraspEvent::set_arm(const std::string& value) {
  _internal_set_arm(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.GraspEvent.arm)
}
inline std::string* GraspEvent::mutable_arm() {
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.GraspEvent.arm)
  return _internal_mutable_arm();
}
inline const std::string& GraspEvent::_internal_arm() const {
  return arm_.Get();
}
inline void GraspEvent::_internal_set_arm(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  arm_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GraspEvent::set_arm(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  arm_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gazebo.msgs.GraspEvent.arm)
}
inline void GraspEvent::set_arm(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  arm_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gazebo.msgs.GraspEvent.arm)
}
inline void GraspEvent::set_arm(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  arm_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gazebo.msgs.GraspEvent.arm)
}
inline std::string* GraspEvent::_internal_mutable_arm() {
  _has_bits_[0] |= 0x00000001u;
  return arm_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GraspEvent::release_arm() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.GraspEvent.arm)
  if (!_internal_has_arm()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return arm_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GraspEvent::set_allocated_arm(std::string* arm) {
  if (arm != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  arm_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), arm,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.GraspEvent.arm)
}
inline std::string* GraspEvent::unsafe_arena_release_arm() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gazebo.msgs.GraspEvent.arm)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return arm_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GraspEvent::unsafe_arena_set_allocated_arm(
    std::string* arm) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (arm != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  arm_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      arm, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gazebo.msgs.GraspEvent.arm)
}

// required string object = 2;
inline bool GraspEvent::_internal_has_object() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool GraspEvent::has_object() const {
  return _internal_has_object();
}
inline void GraspEvent::clear_object() {
  object_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& GraspEvent::object() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.GraspEvent.object)
  return _internal_object();
}
inline void GraspEvent::set_object(const std::string& value) {
  _internal_set_object(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.GraspEvent.object)
}
inline std::string* GraspEvent::mutable_object() {
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.GraspEvent.object)
  return _internal_mutable_object();
}
inline const std::string& GraspEvent::_internal_object() const {
  return object_.Get();
}
inline void GraspEvent::_internal_set_object(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  object_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GraspEvent::set_object(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  object_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gazebo.msgs.GraspEvent.object)
}
inline void GraspEvent::set_object(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  object_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gazebo.msgs.GraspEvent.object)
}
inline void GraspEvent::set_object(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  object_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gazebo.msgs.GraspEvent.object)
}
inline std::string* GraspEvent::_internal_mutable_object() {
  _has_bits_[0] |= 0x00000002u;
  return object_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GraspEvent::release_object() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.GraspEvent.object)
  if (!_internal_has_object()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return object_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GraspEvent::set_allocated_object(std::string* object) {
  if (object != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  object_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), object,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.GraspEvent.object)
}
inline std::string* GraspEvent::unsafe_arena_release_object() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gazebo.msgs.GraspEvent.object)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000002u;
  return object_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GraspEvent::unsafe_arena_set_allocated_object(
    std::string* object) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (object != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  object_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      object, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gazebo.msgs.GraspEvent.object)
}

// required bool attached = 3;
inline bool GraspEvent::_internal_has_attached() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool GraspEvent::has_attached() const {
  return _internal_has_attached();
}
inline void GraspEvent::clear_attached() {
  attached_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool GraspEvent::_internal_attached() const {
  return attached_;
}
inline bool GraspEvent::attached() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.GraspEvent.attached)
  return _internal_attached();
}
inline void GraspEvent::_internal_set_attached(bool value) {
  _has_bits_[0] |= 0x00000004u;
  attached_ = value;
}
inline void GraspEvent::set_attached(bool value) {
  _internal_set_attached(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.GraspEvent.attached)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_grasp_5fevent_2eproto
